version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/PES-BE
file_exists_behavior: OVERWRITE
permissions:
  - object: /home/ubuntu/PES-BE
    owner: ubuntu
    group: ubuntu
hooks:
  AfterInstall:
    - location: deploy.sh
      timeout: 300
      runas: ubuntu